---
title: ""
output: html_document
---
# Annotations (run) – dataset requirements

The dataset with run annotations is supposed to look like this:

<style>
table {
  width: 50%;
}

</style>

|runID |sampleID |rep |
|:-----|:--------|:---|
|F1    |A1       |   1|
|F2    |A1       |   2|
|F3    |A2       |   1|
|F4    |A2       |   2|

## Format specifications

* Only .csv/.txt formats are allowed.
* Separators: 
    * .csv – comma (,)
    * .txt – tab (`\t`)
* Decimal point: dot (.)

**Warning: The file must not contain row names!**

## Column specifications

* First column: *runID* – column with unique IDs for each run in a form of F# (where # is a number). It must consist of the same 'F#' from the column names of abundances dataset – see the help above.

* Second column: *sampleID* – column with sample IDs (one for each patient). It consists of a letter indicating a treatment group and a number indicating the patient
number within the group. E.g. ID A2 stands for the second patient within a
treatment group A. The same sample ID can be assigned to several run IDs.

* Third column: *rep* – column with replicate number. E.g. Run F4 is the second replicate for a patient A2.

* Optional columns: a user can also provide columns with a batch number, the order of a replicate within the batch and date-time column.

<span style="font-size:1.5em;">**The form of the above column names is mandatory!**</span>
